config/routes.rb
Rails.application.routes.draw do
  resources :devices do
    get 'pin_high', to: 'devices#pin_high'
    get 'pin_low', to: 'devices#pin_low'
    get 'serial_out', to: 'devices#serial_out'
  end


  get 'static_pages/home'
  get 'static_pages/help'
  get 'static_pages/about'

  root 'static_pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/device.rb
class Device < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper ApplicationHelper
end

app/controllers/devices_controller.rb
class DevicesController < ApplicationController
  before_action :set_device, only: [:show, :edit, :update, :destroy, :pin_high, :pin_low]
  

  require 'rpi_gpio'
  require 'serialport'
  # GET /devices
  # GET /devices.json
  helper DevicesHelper
  def index
    @devices = Device.all
  end

  # GET /devices/1
  # GET /devices/1.json
  def show
  end

  # GET /devices/new
  def new
    @device = Device.new
  end

  # GET /devices/1/edit
  def edit
  end

  # POST /devices
  # POST /devices.json
  def create
    @device = Device.new(device_params)

    if @device.io == 1
      RPi::GPIO.setup @device.pin, :as => :input
    else
      RPi::GPIO.setup @device.pin, :as => :output
    end

    respond_to do |format|
      if @device.save
        format.html { redirect_to static_pages_home_path, notice: 'Device was successfully created.' }
        format.json { render :show, status: :created, location: @device }
      else
        format.html { render :new }
        format.json { render json: @device.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /devices/1
  # PATCH/PUT /devices/1.json
  def update
    respond_to do |format|
      if @device.update(device_params)
        format.html { redirect_to static_pages_home_path, notice: 'Device was successfully updated.' }
        format.json { render :show, status: :ok, location: @device }
      else
        format.html { render :edit }
        format.json { render json: @device.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /devices/1
  # DELETE /devices/1.json
  def destroy
    @device.destroy
    respond_to do |format|
      format.html { redirect_to static_pages_home_path, notice: 'Device was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def pin_high
    RPi::GPIO.set_high @device.pin
    puts "Turning pin #{@device.pin} ON"
  end

  def pin_low
    RPi::GPIO.set_low @device.pin
    puts "Turning pin #{@device.pin} OFF"
  end

  def serial_out
    puts "Entering serial_out routine"
    text = params[:serial_text]
    #puts text.class
    text = [text].pack('H*')
    text = text.unpack('C*')
    text.each_entry do |byte|
      #puts "BYTE"
      $ser.write "#{byte.chr}"
    end 
    #$ser.write "#{text.each_entry.to_s}"
    puts "Sending #{text.each_entry do |e| e.to_s end} command to UART0"
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_device
      @device = Device.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def device_params
      params.require(:device).permit(:id, :name, :description , :deviceFunction , :node_id, :io, :pin, :serial_text)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
$gpio_initialized = false


  def home
    @devices = Device.all
  end

  def help

  end

  def about

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  require 'rpi_gpio'

#    def setup_gpio
#    RPi::GPIO.set_numbering :board
#    @devices = Device.all
#    @devices.each do|d|
#      if @d.io == 1
#        RPi::GPIO.setup @device.pin, :as => :input
#      else
#        RPi::GPIO.setup @device.pin, :as => :output
#      end
#    end
#  end
end

app/helpers/devices_helper.rb
module DevicesHelper
  require 'rpi_gpio'
  require 'serialport'
  
  def gpio_setup
    puts "***entered gpio_setup routine***"
    RPi::GPIO.set_numbering :board
    #@devices.first.name
    $ser = SerialPort.new("/dev/ttyUSB0", 57600, 8, 1, SerialPort::NONE)
    if @devices.first.id != nil
      puts "***devices exist***"
      puts "#{$gpio_initialized}"
      puts "#{@devices.first.io}"
      puts "Pi initialized"
      @devices.each do |d|
        if d.io == 1
          RPi::GPIO.setup d.pin, :as => :input
        else
          RPi::GPIO.setup d.pin, :as => :output
        end
      end
      $gpio_initialized = true
    end
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/devices/_form.html.erb
<%= form_for(device) do |f| %>
  <% if device.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(device.errors.count, "error") %> prohibited this device from being saved:</h2>

      <ul>
      <% device.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>

  <div class="field">
    <%= f.label :Function %>
    <%= f.number_field :deviceFunction %>
  </div>

  <div class="field">
    <%= f.label :node_id %>
    <%= f.number_field :node_id %>
  </div>

  <div class="field">
    <%= f.label :io %>
    <%= f.number_field :io %>
  </div>

  <div class="field">
    <%= f.label :pin %>
    <%= f.number_field :pin %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/devices/edit.html.erb
<h1>Editing Device</h1>

<%= render 'form', device: @device %>

<%= link_to 'Back', static_pages_home_path, class: "btn btn-primary" %>

app/views/devices/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Devices</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @devices.each do |device| %>
      <tr>
        <td><%= link_to 'Show', device %></td>
        <td><%= link_to 'Edit', edit_device_path(device) %></td>
        <td><%= link_to 'Destroy', device, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Device', new_device_path %>

app/views/devices/new.html.erb
<h1>New Device</h1>

<%= render 'form', device: @device %>

<%= link_to 'Back', static_pages_home_path %>

app/views/devices/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_device_path(@device) %> |
<%= link_to 'Back', static_pages_home_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GpioTest</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="jumbotron text-center">
      <h1>Device Test</h1>
  
      <p><a class="btn btn-primary btn-lg" href="/static_pages/home" role="button">Home</a></p>
    </div>
    <div class="container-fluid">
      <%= yield %>
    </div>
  </body>
</html>

app/views/static_pages/about.html.erb
<h1>StaticPages#about</h1>
<p>Find me in app/views/static_pages/about.html.erb</p>

app/views/static_pages/help.html.erb
<h1>StaticPages#help</h1>
<p>Find me in app/views/static_pages/help.html.erb</p>

app/views/static_pages/home.html.erb
<!-- check to see if Devices are nil, and if not, display them-->
<% if @devices.first != nil %>
  <%if $gpio_initialized == false%>
    <% gpio_setup %> 
  <%end%>

<h1>Devices</h1>
Device Initialized Status: 
<%= $gpio_initialized %>

<div class="panel panel-default">
  <!-- Default panel contents -->
  <div class="panel-heading">Devices</div>

  <!-- Table -->
  <table class="table">
    <tr>
      <td><strong>Device Name</strong></td>
      <td><strong>Description</strong></td>
      <td><strong>Function</strong></td>
      <td><strong>Node ID</strong></td>



      <%@devices.each do |d|%>
        <tr>
          <td><%= d.name%></td>
          <td><%= d.description%></td>
          <td><%= d.deviceFunction%></td>
          <td><%= d.node_id%></td>
          <td>
            <%if d.io == 0%>
              <div class="btn-group" role="group" aria-label="...">
                <div class="btn-group" role="group">
                  <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <%=d.name%>, <%= d.id%>
                    <span class="caret"></span>
                  </button>
                  <ul class="dropdown-menu">
                    <li><%= link_to 'PIN_ON', device_pin_high_path(d,:id => d.id), remote: true%></li>
                    <li><%= link_to 'PIN_OFF', device_pin_low_path(d,:id => d.id), remote: true%></li>
                    <!-- Transmit a Text Command -->
                    <li><%= link_to 'transmit single hex', device_serial_out_path(d, :serial_text => "55"),  remote: true%></li>
                    <li><%= link_to 'Light ON', device_serial_out_path(d, :serial_text => "7E001017010013A200406C019F00020244300569"),  remote: true%></li>
                    <li><%= link_to 'Light OFF', device_serial_out_path(d, :serial_text => "7E001017010013A200406C019F0002024430046A"),  remote: true%></li>
                  </ul>
                </div>
              </div>
            <%end%>
          </td>
          <td><%= link_to 'Edit', edit_device_path(d), class: 'btn btn-warning' %></td>

          <td><%= link_to 'Destroy', d, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %></td>
        </tr>
      <%end%>
    <%end%>
  </tr>
  </table>
</div>

<%= link_to 'New Device', new_device_path, class: 'btn btn-primary' %>